#PytorchModel: example-models/two_layer_model.pt
PytorchModel: example-models/three_layer_model.pt
OutputDir: my-hls-dir-3L
ProjectName: myproject
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
DefaultPrecision: ap_fixed<18,8> 
