KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_weights.h5
OutputDir: my-hls-test
ProjectName: myproject
Device: Arria10
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
DefaultPrecision: ac_fixed<16,6> 
